nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['*']
        max_age: 3600
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    
    paths:
        '^/api/upload-excel':
            allow_origin: ['*']
            allow_headers: '*'
            allow_methods: ['POST', 'GET']
